In [69]:
#installs numpy for prompts 5, 6, 7
!pip install numpy

In [70]:
#imports numpy
import numpy

In [71]:
#imports math for prompts 3, 7
import math

In [72]:
"""
1. Create a function that converts a list of Fahrenheit temperatures
to Celsius and returns the list of the resulting temperatures.
"""
def fahrenheittocelsiuslist(fahrenheittemperatures):
  celsiustemperatures = []
  #conversion from fahrenheit to celcius
  for tempf in fahrenheittemperatures:
      tempc = (tempf - 32) * 5/9
      #applies to fahrenheit conversion to the list
      celsiustemperatures.append(tempc)
  #returns converted temperatures
  return celsiustemperatures
fahrenheittemps = [10, 70, 98, 50]
celsiustemps = fahrenheittocelsiuslist(fahrenheittemps)
#prints original list and converted list
print(f"Farenheit temperatures: {fahrenheittemps}")
print(f"Celcius temperatures:{celsiustemps}")

Farenheit temperatures: [10, 70, 98, 50]
Celcius temperatures:[-12.222222222222221, 21.11111111111111, 36.666666666666664, 10.0]


In [73]:
"""
2. Create a function that returns the second-smallest and
second-largest numbers in a list.
"""
#defines function
def findsecondsmallestandlargest(numbers):
  #checks if list has less than two numbers
  #if only two, return no numbers
  if len(numbers) < 2:
    return None, None
  #removes duplicate numbers
  #sorts the list into ascending order
  uniquenumbers = sorted(list(set(numbers)))
  if len(uniquenumbers) < 2:
    return None, None
  #second smallest number is at index 1 of the sorted list
    #it's at index 1 because python's first number in a sorted list is index 0
  #second largest number is at index -2 of the sorted list
  return uniquenumbers[1], uniquenumbers[-2]
#list
numbers = [1, 1384, 228, 49, 72, 996, -25, 18888, 2000000, 7, -745]
secondsmallest, secondlargest = findsecondsmallestandlargest(numbers)
#prints responses
print(numbers)
print(f"Second smallest: {secondsmallest}")
print(f"Second largest: {secondlargest}")

[1, 1384, 228, 49, 72, 996, -25, 18888, 2000000, 7, -745]
Second smallest: -25
Second largest: 18888


In [74]:
"""
3. Create a 2D point class with an x and y, and a function that
returns the distance from the point to the origin.
"""
class Point2D:
    #sets point in 2D space
    def __init__(self, x, y):
    #assigns to x and y coordinates
      self.x = x
      self.y = y
    #solves for hypotenuse
    def distance_from_origin(self):
      return math.sqrt(self.x**2 + self.y**2)
# Example Usage
if __name__ == "__main__":
  #point 1 coordinates
  point1 = Point2D(7, -7)
  #prints out coordinates and distance from origin (0, 0)
  print(f"Point 1 coordinates: ({point1.x}, {point1.y})")
  print(f"Distance of Point 1 from origin: {point1.distance_from_origin()}")
  #point 2 coordinates
  point2 = Point2D(-3, -9)
  print(f"Point 2 coordinates: ({point2.x}, {point2.y})")
  print(f"Distance of Point 2 from origin: {point2.distance_from_origin()}")

Point 1 coordinates: (7, -7)
Distance of Point 1 from origin: 9.899494936611665
Point 2 coordinates: (-3, -9)
Distance of Point 2 from origin: 9.486832980505138


In [75]:
"""
4. Create a basic chess piece class with its position(use two numbers
instead of a letter and number) and color. Then create rook, bishop,
and queen subclasses, adding a moves function that returns a list of
possible moves based on its position.
"""
#I didn't really understand what to do for this-

'\n4. Create a basic chess piece class with its position(use two numbers\ninstead of a letter and number) and color. Then create rook, bishop,\nand queen subclasses, adding a moves function that returns a list of\npossible moves based on its position.\n'

In [76]:
"""
5. Create a 6 x 6 numpy array of 0s and change a diagonal to 1s.
"""
!pip install numpy
import numpy #for some reason it would produce an error if i didn't install and import numpy into the code again
#creates a 6x6 numpy array filled with zeros
array = numpy.zeros((6, 6))
#changes the diagonal to 1
numpy.fill_diagonal(array, 1)
#prints the array
print(array)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [83]:
"""
6. Create a numpy array of numbers from 1-100, then change every other
odd to -1.
"""
#creates a numpy array of numbers from 1 to 100
array = numpy.arange(1, 101)
#searches and identifies odd numbers
odd = numpy.where(array % 2 == 1)[0]
#change every other odd number to -1
#uses slicing with a step of 2 to select every other value from the odd
array[odd[::2]] = -1
print(array)

[ -1   2   3   4  -1   6   7   8  -1  10  11  12  -1  14  15  16  -1  18
  19  20  -1  22  23  24  -1  26  27  28  -1  30  31  32  -1  34  35  36
  -1  38  39  40  -1  42  43  44  -1  46  47  48  -1  50  51  52  -1  54
  55  56  -1  58  59  60  -1  62  63  64  -1  66  67  68  -1  70  71  72
  -1  74  75  76  -1  78  79  80  -1  82  83  84  -1  86  87  88  -1  90
  91  92  -1  94  95  96  -1  98  99 100]


In [90]:
"""
7. Create a 3d PointCloud class, which stores any number of 3D points
in an array. Provide functions to add new points, remove points, and
find the closest point to an input point.
"""
#imports math
import math
#class to represent pointcloud
class PointCloud:
    #initialzes pointcloud
    def __init__(self, points=None):
        if points is None:
            self.points = numpy.empty((0, 3))
        else:
            self.points = numpy.array(points)
            if self.points.ndim != 2 or self.points.shape[1] != 3:
                raise ValueError("Invalid")
    #adds one point
    def add_point(self, point):
        if not isinstance(point, (list, tuple)) or len(point) != 3:
            #if value is invalid:
            raise ValueError("Invalid")
        self.points = numpy.vstack((self.points, np.array(point).reshape(1, 3)))
    #adds multiple points
    def add_points(self, points):
        new_points = numpy.array(points)
        if new_points.ndim != 2 or new_points.shape[1] != 3:
            #if value is invalid
            raise ValueError("Invalid")
        self.points = numpy.vstack((self.points, new_points))
    #removes one point
    def remove_point(self, index):
        if not isinstance(index, int) or index < 0 or index >= len(self.points):
            #if index is invalid:
            raise IndexError("Invalid")
        self.points = numpy.delete(self.points, index, axis=0)
    #removes multiple points
    def remove_points(self, indices):
        indices = numpy.array(indices)
        if not all(isinstance(i, int) and 0 <= i < len(self.points) for i in indices):
            #if index is invalid:
            raise IndexError("Invalid")
        self.points = numyp.delete(self.points, indices, axis=0)
    #finds the closest point in the pointcloud. returns "None" if the pointcloud is empty
    def find_closest_point(self, point):
        if len(self.points) == 0:
             return None
        point = numpy.array(point)
        if point.shape != (3,):
             #if value is invalid
             raise ValueError("Invalid")
        distances = numpy.sqrt(np.sum((self.points - point)**2, axis=1))
        closest_index = math.sqrt(x**2 + y**2 + z**2)
        return self.points[closest_index], closest_index
    #returns the number of points in the point cloud
    def __len__(self):
        return len(self.points)
    #returns a string that represents the point cloud
    def __str__(self):
        return f"PointCloud with {len(self.points)} points:\n{self.points}"

print("Hello, World")
"""I don't know if the formatting is different, but when I left one indetation where
 it corresponds, it produced an error, but if I left two indentations, it worked.
 Also, I don't know if it's supposed to print anything out when it responds. I wanted
 to check if the notebook was working so I printed Hello, World, just to make sure
 every time."""

Hello, World


"I don't know if the formatting is different, but when I left one indetation where\n it corresponds, it produced an error, but if I left two indentations, it worked.\n Also, I don't know if it's supposed to print anything out when it responds. I wanted\n to check if the notebook was working so I printed Hello, World, just to make sure \n every time."